SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE SCHEMA IF NOT EXISTS `jfshare` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;

USE `jfshare`;

CREATE  TABLE IF NOT EXISTS `jfshare`.`jfs_lgsts_delivery` (
  `id` BIGINT(20) NOT NULL ,
  `order_id` BIGINT(20) NOT NULL ,
  `delivery_id` VARCHAR(255) NULL DEFAULT NULL ,
  `order_type` INT(11) NULL DEFAULT NULL ,
  `product_name` VARCHAR(255) NULL DEFAULT NULL ,
  `remark` VARCHAR(400) NULL DEFAULT NULL ,
  `delivery_company` VARCHAR(255) NULL DEFAULT NULL ,
  `latest_time` DATETIME NULL DEFAULT NULL ,
  `latest_status` VARCHAR(255) NULL DEFAULT NULL ,
  `latest_processor` VARCHAR(255) NULL DEFAULT NULL ,
  `detail` TEXT NULL DEFAULT NULL ,
  PRIMARY KEY (`id`) ,
  UNIQUE INDEX `jfs_lgsts_delivery_order_delivery` (`order_id` DESC, `delivery_id` DESC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
